[package]
name = "Rusty_Skywalker"
version = "0.1.0"
authors = ["Shubham Kumar <Shubhamkrai123@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.5"
percent-encoding = "2.1.0"
